# Generated by Django 5.2.16 on 2026-08-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='User',
        ),
    ]
